---
minimum_pre_commit_version: 2.9.2
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-merge-conflict      # Check for files that contain merge conflict strings.
  - id: trailing-whitespace       # Trims trailing whitespace.
    args: [--markdown-linebreak-ext=md]
  - id: mixed-line-ending         # Replaces or checks mixed line ending.
    args: [--fix=lf]
  - id: end-of-file-fixer         # Makes sure files end in a newline and only a newline.
  - id: check-merge-conflict      # Check for files that contain merge conflict strings.
  - id: check-ast                 # Simply check whether files parse as valid python.

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
    name: Upgrade Python Code
    args: [--py3-plus]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.6
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    args: [--line-length, '100']

- repo: https://github.com/s0undt3ch/pre-commit-populate-pylint-requirements
  rev: master
  hooks:
  - id: populate-pylint-requirements
    files: ^requirements\.txt$

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.6.0
  hooks:
  - id: pylint
    name: PyLint
    args: [--output-format=parseable, --rcfile=.pylintrc]
    additional_dependencies:
    - coverage >= 5.3
    - pytest>=6.1.0
    - pyzmq
